name: Deploy to itch.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to itch.io
        uses: itchyny/butler-action@v1.3.0  # ¡Versión más reciente!
        with:
          butler-api-key: ${{ secrets.BUTLER_API_KEY }}
          user: RVDveloper
          game: Racinfi
          directory: build
          channel: web