name: Deploy to itch.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to itch.io
        uses: manleydev/butler-publish-itchio-action@v1.0.0
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          username: RVDveloper  # Cambia esto
          game: Racinfi       # Cambia esto
          version: ${{ github.sha }}
          channel: web
          zip: false
          directory: Build      # Asegúrate que coincide con tu ruta