name: Deploy to itch.io

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          sudo mv butler /usr/local/bin/
          
      - name: Push to itch.io
        run: |
          butler push build RVDveloper/Racingfi:web --userversion ${{ github.sha }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}